backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/images/cms" # Media files will be stored in the repo under images/uploads

collections:
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }

      # Company Information
      - label: "Company Information"
        name: "company"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Press Kit", name: "press", widget: "string", required: false }
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

      # Global Navigation
      - label: "Navigation"
        name: "navigation"
        widget: "list"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
      
      # First Section
      - label: "Section One"
        name: "sectionOne"
        widget: "object"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown", required: false }
      
      # Second Section
      - label: "Section Two"
        name: "sectionTwo"
        widget: "object"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Principles"
            name: "principles"
            widget: "list"
            field: { label: Text, name: text, widget: string }

      # Section Three
      - label: "Section Three"
        name: "sectionThree"
        widget: "object"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Companies"
            name: "companies"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Type, name: type, widget: string }
              - { label: Description, name: description, widget: string, required: false }
              - { label: Mission, name: mission, widget: string, required: false }
              - { label: Industry, name: industry, widget: string, required: false }
              - { label: Website, name: website, widget: string, required: false }

      # Section Four
      - label: "Section Four"
        name: "sectionFour"
        widget: "object"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: location, name: location, widget: string }
              - { label: Description, name: description, widget: string, required: false }
              - label: Social
                name: social
                widget: object
                required: false
                collapsed: true
                fields:
                  - { label: Twitter, name: twitter, widget: string, required: false }
                  - { label: LinkedIn, name: linkedin, widget: string, required: false }

      # Section Five
      - label: "Section Five"
        name: "sectionFive"
        widget: "object"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Link"
            name: "link"
            widget: "object"
            collapsed: true
            fields:
              - { label: Text, name: text, widget: string }
              - { label: Location, name: location, widget: string }
              - { label: Title, name: title, widget: string }
